{
 "title": "JJNet",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Link Priston - Down",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Borda" },
     "item": {
      "filter": "Interface Link PristonNet(): Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LAN - Geral Down",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Barragem" ],
       "text": "setAlias(Barragem)"
      }
     ],
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1101-Barragem(): Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Fontes" ],
       "text": "setAlias(Fontes)"
      }
     ],
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1102-FONTES(): Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Progresso" ],
       "text": "setAlias(Progresso)"
      }
     ],
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1104-PROGRESSO(): Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Marsilac" ],
       "text": "setAlias(Marsilac)"
      }
     ],
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1103-MARSILAC-FIBRA(): Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Clientes Online",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": { "filter": "PPPoE Active Connections" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LAN - Geral Up",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 13, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Barragem" ],
       "text": "setAlias(Barragem)"
      }
     ],
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1101-Barragem(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Fontes" ],
       "text": "setAlias(Fontes)"
      }
     ],
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1102-FONTES(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Progresso" ],
       "text": "setAlias(Progresso)"
      }
     ],
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1104-PROGRESSO(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Marsilac" ],
       "text": "setAlias(Marsilac)"
      }
     ],
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1103-MARSILAC-FIBRA(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Barragem",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1101-Barragem(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Link Priston - Up",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Borda" },
     "item": {
      "filter": "Interface Link PristonNet(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Progresso",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1104-PROGRESSO(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Via Veloz - Down",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Borda" },
     "item": {
      "filter": "Interface sfp-sfpplus2-WAN2(Via Veloz): Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Fontes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1102-FONTES(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Link Via Veloz - Up",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Borda" },
     "item": {
      "filter": "Interface sfp-sfpplus2-WAN2(Via Veloz): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 2, "w": 3, "x": 10, "y": 6 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": { "filter": "PPPoE Active Connections" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Marsilac",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1103-MARSILAC-FIBRA(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SW-CASA",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNET - Barragem" },
     "item": {
      "filter": "Interface @J&JNET_Av Brasil(ok): Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SW-PROGRESSO",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNET - Barragem" },
     "item": {
      "filter": "Interface @J&JNET_Av Brasil(ok): Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SW-FONTES",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 6, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNET - Barragem" },
     "item": {
      "filter": "Interface @J&JNET_Av Brasil(ok): Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SW-DONIZETE",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNET - Barragem" },
     "item": {
      "filter": "Interface @J&JNET_Av Brasil(ok): Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P4",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW1 - Casa Jefferson" },
     "item": {
      "filter": "Interface Gi1/0/4 : copper: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P25",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW1 - Casa Jefferson" },
     "item": {
      "filter": "Interface Te1/0/25 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P26",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW1 - Casa Jefferson" },
     "item": {
      "filter": "Interface Te1/0/26 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P25",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW2 - Progresso" },
     "item": {
      "filter": "Interface port 25: Gigabit Copper: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P27",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW2 - Progresso" },
     "item": {
      "filter": "Interface port 27: Gigabit Fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P28",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW2 - Progresso" },
     "item": {
      "filter": "Interface port 28: Gigabit Fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P28",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW3 - Fontes" },
     "item": {
      "filter": "Interface gigabitEthernet 1/0/1 : copper: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P9",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW3 - Fontes" },
     "item": {
      "filter": "Interface gigabitEthernet 1/0/9 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P10",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW3 - Fontes" },
     "item": {
      "filter": "Interface gigabitEthernet 1/0/10 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P9",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW4 - Donizete" },
     "item": {
      "filter": "Interface gigabitEthernet 1/0/9 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P10",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW4 - Donizete" },
     "item": {
      "filter": "Interface gigabitEthernet 1/0/10 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SW-Base_embura",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNET - Barragem" },
     "item": {
      "filter": "Interface @J&JNET_Av Brasil(ok): Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SW-KM47",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 4, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNET - Barragem" },
     "item": {
      "filter": "Interface @J&JNET_Av Brasil(ok): Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SW-KM49",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNET - Barragem" },
     "item": {
      "filter": "Interface @J&JNET_Av Brasil(ok): Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RB Barragem",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNET - Barragem" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RB Progresso",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNET - Progresso" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RB Fontes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNET - Jd_Fontes" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RB Marsilac",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNET - Marsilac" },
     "item": { "filter": "ICMP ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P9",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW5 - Base_embura" },
     "item": {
      "filter": "Interface gigabitEthernet 1/0/9 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P10",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW5 - Base_embura" },
     "item": {
      "filter": "Interface gigabitEthernet 1/0/10 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P9",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW5 - KM47" },
     "item": {
      "filter": "Interface gigabitEthernet 1/0/9 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P10",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW5 - KM47" },
     "item": {
      "filter": "Interface gigabitEthernet 1/0/10 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P9",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW5 - KM49" },
     "item": {
      "filter": "Interface gigabitEthernet 1/0/9 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "P10",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "SW5 - KM49" },
     "item": {
      "filter": "Interface gigabitEthernet 1/0/10 : fiber: Operational status"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Rede Interna Geral",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1101-Barragem(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1104-PROGRESSO(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1102-FONTES(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Con. PPPoE" },
     "item": {
      "filter": "Interface VID1103-MARSILAC(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Link PristonNet",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Borda" },
     "item": {
      "filter": "Interface Link PristonNet(): Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Borda" },
     "item": {
      "filter": "Interface Link PristonNet(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Link Via Veloz",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Borda" },
     "item": {
      "filter": "Interface sfp-sfpplus2-WAN2(Via Veloz): Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Borda" },
     "item": {
      "filter": "Interface sfp-sfpplus2-WAN2(Via Veloz): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "LAN TOTAL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Borda" },
     "item": {
      "filter": "Interface LACP-LAN(): Bits received"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "group": { "filter": "J_J_Net" },
     "host": { "filter": "JJNet - Borda" },
     "item": {
      "filter": "Interface LACP-LAN(): Bits sent"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}